server:
  port: 80
#2.配置相关信息
spring:
  dataSource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useSSL=false
    username: root
    password: root